### ISSUE TITLE
Instructions for installing / configuring temperature machine UI

### ISSUE THREAD

**Issue by praxidice01** [tobyweston/temperature-machine#100]
I would greatly appreciate pedantic instructions for installing / configuring the temperature machine UI.  Everything else to do with temperature machine is well documented but unless I've missed something very significant, there doesn't appear as much as a sentence about the UI.  It goes without saying that without a way to view the temperature records, temperature machine isn't much use.  Presumably there is relevant documentation SOMEWHERE as without it, everyone would be raising the issue. I don't believe I'm going blind but after hours of searching with no results, I am EXTREMELY frustrated.

**Comment by praxidice01** [comment]
A map for locating things would be nice.  As well as the instructions for installing / configuring the UI, I'm also searching in vain for the plans to make the add-0n boards. It goes without saying that they must be here someplace, but WHERE ?

**Comment by tobyweston** [comment]
The UI comes with the application.

If you’ve set it up, you just need to point a browser to the address documented.

**Comment by tobyweston** [comment]
The plans are on the root of the GitHub project https://github.com/tobyweston/temperature-machine/blob/master/pizero.fzz

When I have some time, I’ll write up how you get them printed, for now google .fzz for some tips

**Comment by praxidice01** [comment]
T

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by praxidice01** [comment]
Thanks. Finally found the pizero.fzz and some information on using it.  At present I've had to put that on hold until I can figure what to do with the UI, or rather the total lack of a UI. 

A far bigger / more frustrating problem giving me the heeby-jeebies is the UI. I'm completely in the dark with that. Can you advise where to find instructions about installing / configuring the UI?  It doesn't appear to know it was supposed to install with the rest of the temperature machine stuff. As far as I'm aware, everything else is working fine but I can't view any data, whether locally or remotely.  As I said elsewhere, the only options I'm aware of are to assign a public IP to the RPI or doing a full reinstall of raspbian with a GUI.  If I have a browser in the PRI, just maybe I'll be able to see the data.  

if the UI 'comes with the application', what would prevent it working or being visible ?  So far, the only chance I've had of seeing the UI are from a laptop or desktop running current version Windows 10. Maybe Windows 10 doesn't like rasbian or something to do with temperature machine. It wouldn't be the first time Microsoft updates broke something. Guess I could try a monitor and keyboard on one of the (currently headless) Windows XP or Windows 7 devices I  have.  Actually I'll have XPe and Windows Embedded Standard too.

Unless you have any other ideas, I see the possible options as 

(1)    A Windows XP / 7 / whatever machine

(2)    A public IP on the RPI

(3)    A full GUI raspbian

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by praxidice01** [comment]
Just discovered https://temperature-machine.com/docs/hacking.html

Build the Web App

The front-end is hosted in another project, https://github.com/tobyweston/temperature-machine-ui. Development goes on over there but when it’s ready to bring into the temperature-machine, run the following script.

build-webapp.sh

It will download the latest version of the web-app, build it and overwrite the content of src/main/resources.

The resources folder is statically served by Server.scala.

I know precisely nothing about scala, but could this be the missing part of the puzzle  ?

**Comment by tobyweston** [comment]
Ignore the other project, it’s how I build it. Users won’t need to build it.

The UI is deployed with the app, there’s nothing extra to do. You should have it already.

I think you’re missing a basic step. What address do you type into the browser? what’s the ping command you use? What’s in the log?

**Comment by tobyweston** [comment]
Btw it’s helpful to stick to one forum for help. Having emails, disqus chats is confusing as they may or may not show the same name as the author so I can’t tell if there’s one problem or multiple!

**Comment by praxidice01** [comment]
Tried 192.168.1.5:11900 and 192.168.1.5:11900/temperatures

ping 192.168.1.5 (works fine)

don’t know what log you mean



________________________________

**Comment by tobyweston** [comment]
You’re trying:

http://192.168.1.5:11900

From a browser? What does the result look like in the browser?

The log is under ~/.temperature 

If you look in it, any errors with would appear. Are you happy with bash commands to find and open the log file?

You can also try curling the above url if you’re more comfortable at the terminal.

**Comment by praxidice01** [comment]
FWIW, that ‘~’ symbol bothers me ..... I can follow a definite path, but something as nebulous as ~ has me running in circles


________________________________

**Comment by praxidice01** [comment]
Can’t get at the log due to a keyboard mapping issue.  Regular characters are fine but most symbols don’t correspond to the keys.  Its only a common or garden variety keyboard but its got its wires crossed somehow

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by praxidice01** [comment]
No errors in the log

Only thing in it is what looks like time and date, followed by

[sun::jmxremote] managementCONFIG JMX Connector ready at:  service: jmx:rml:///jndi/rml://raspberrypi:42999/jmxrmi

I guess that is fine however its martian to me

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Edward Kelly <brizzie@live.com>
Sent: Wednesday, November 13, 2019 6:16:32 AM
To: tobyweston/temperature-machine <reply@reply.github.com>
Subject: RE: [tobyweston/temperature-machine] Instructions for installing / configuring temperature machine UI (#100)


FWIW, that ‘~’ symbol bothers me ..... I can follow a definite path, but something as nebulous as ~ has me running in circles





________________________________

**Comment by praxidice01** [comment]
No obvious log error, tried other operating systems and public IP ..... no joy

Did complete reinstall of GUI rasbian, updating at present.

Will follow your instructions for installing temperature machine and hope for better result this time. At least there should be no possible communication issue with viewing the data locally. Once that is working, I’ll assign a public IP to the RPI and work on viewing the data remotely.

The trick that worked with keyboard mapping was to set US generic keyboard. I notice a number of reports which mention keyboard issues with the default raspbian setup ... seems it only works properly for a lot of people with US keyboard mapping.


________________________________
From: Edward Kelly <brizzie@live.com>
Sent: Wednesday, November 13, 2019 7:42:39 AM
To: tobyweston/temperature-machine <reply@reply.github.com>
Subject: RE: [tobyweston/temperature-machine] Instructions for installing / configuring temperature machine UI (#100)


No errors in the log



Only thing in it is what looks like time and date, followed by



[sun::jmxremote] managementCONFIG JMX Connector ready at:  service: jmx:rml:///jndi/rml://raspberrypi:42999/jmxrmi



I guess that is fine however its martian to me



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10



________________________________
From: Edward Kelly <brizzie@live.com>
Sent: Wednesday, November 13, 2019 6:16:32 AM
To: tobyweston/temperature-machine <reply@reply.github.com>
Subject: RE: [tobyweston/temperature-machine] Instructions for installing / configuring temperature machine UI (#100)


FWIW, that ‘~’ symbol bothers me ..... I can follow a definite path, but something as nebulous as ~ has me running in circles





________________________________

**Comment by tobyweston** [comment]
I'm going to close this issue and suggest we try and resolve it in one place. You're already posting to Gitter, so suggest we do it there. Gitter is better suited to the kinds of questions where more people can join in and ask clarifying questions.

BTW, you appear as two different users on Gitter (@praxidice01 and `praxidice` there. I also see posts elsewhere with your full name - it's a bit difficult to get continuity if you cross post and I can't tell who's asking what. I've closed comments on the original blog post (disqus) for the same reason.

**Comment by tobyweston** [comment]
BTW `~` is a shortcut for the user's home, so everywhere you see it, substitute it with `/home/pi`.

So

```
~/.temperature
```

is the same as

```
/home/pi/.temperature
```

**Comment by praxidice01** [comment]
FWIW, I did try to use the same ID but seems it has been used by someone else.  Will probably be a bit quiet for a few days pending receipt of the Zero adaptors and whatever messing around to get the speed issue sorted. I figure that anything running as ridiculously slow as my setup is certain to exhibit weird bugs.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
