### ISSUE TITLE
start-server.sh file missing

### ISSUE THREAD

**Issue by Totoleheros** [tobyweston/temperature-machine#105]
Hi,

I had a raspberry (hostname= raspberrypi) that was running temperature machine. I want to add a new raspberry (hostname= pigrandlabo) that should be a client (and the former would be the server).

I have erased the rrd database from the server, changed the'~/.temperature/temperature-machine.cfg' like this

`# valid values "client" or "server" only`
`mode = "server"`
`hosts = ["pigrandlabo", "raspberrypi"]`

And I have change the /etc/rc.local like this:

`su - pi -c 'cd /home/pi/code/temperature-machine && ./start-server.sh pigrandlabo raspberrypi &'`

But I have this message: -su: ./start-server.sh: No such file or directory

Indeed, in the '/home/pi/code/temperature-machine' directory, there is no start-server.sh file (only start.sh)

How can I get this start-server.sh file?

Thank you in advance!!

**Comment by tobyweston** [comment]
`start-server` and `start-client` were from a previous version of TM. If you install via `apt-get`, they're no longer needed.

See https://temperature-machine.com/docs/getting_started/installing.html for some details.
