### ISSUE TITLE
Export Data & Time resolution

### ISSUE THREAD

**Issue by Totoleheros** [tobyweston/temperature-machine#24]
1/ Would be nice to have the possibility to export the data (tab.txt or csv).

2/ Also, would be nice to have the possibility to change the timing of the temperature sampling.

3/ Finally, if one could - from the web interface - to reset the data stored in the ~/temperature.rrd

**Comment by tobyweston** [comment]
1. I have something I've been using to debug things. It's on a branch but https://github.com/tobyweston/temperature-machine/blob/bf81f043d5fc2cc802b1ae9ee7760101c354eb90/src/test/scala/bad/robot/temperature/ConvertJsonToCsv.scala will create a CSV from JSON. If you can wait for a bit, I'll be merging it back to master and can make it usable / add it in properly. If not, you can hack about with it to get you started.

2. I've raised #26 

3. Good idea. It's easier (for me) to track these things as an issue per request. Do you want to raise one for 1 and 3? Then close this one?

**Comment by Totoleheros** [comment]
Thank you. I have open #27 and #28 issues for the points 1/ and 3/ as requested.

**Comment by tobyweston** [comment]
As these have been split, closing for now.
