### ISSUE TITLE
I can't find ~/.temperatures

### ISSUE THREAD

**Issue by Cloudedhouse** [tobyweston/temperature-machine#29]
Where is the above please?

I think it's essential to have access to it in order to make changes such as to the hostname etc

Many thanks

**Comment by tobyweston** [comment]
Can you give more context what you're trying to do.

The working folder for temperature machine is `~/,temperature`. You'll find the images, source RRD etc there.

`~` means the user's home directory (it's unix shorthand). In this case, I mean the `pi` user. So when you're logged in as `pi`, you can type:

```
cd ~
ls -la
```
and if temperature-machine has ever been run, you'll see the `.temperature` folder. `cd` into that.

The long hand is ` /home/pi` so you could always type `cd  /home/pi`. Make sure you're logged in as `pi`.

**Comment by Cloudedhouse** [comment]
Ah, found it, I had to enable Root following these instructions, thanks very much.
```
# sudo -i
# vi /etc/ssh/sshd_config
From, PermitRootLogin without-password
To, PermitRootLogin yes
# /etc/init.d/ssh restart
```
