### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by tobyweston** [tobyweston/temperature-machine#32]
From @singh763173
 
> Apologies, me again - Any chance you might be able to help me write a cron job that can query the domain.com/temperature file and copy that contents into a CSV file? 
> I'm thinking that I can create a csv with three columns, date, time, temp and then collect the data and work with that - what do you think?

**Comment by tobyweston** [comment]
Couple of questions: what are you trying to achieve here? We might be able to do something longer term? Is it related to #23 ? Can you give me some more background? There's a CSV export but it only works for the last 24 hours so may not be what you want.

**Comment by singh763173** [comment]
it is indeed related to #23 - I'm wanting to play with powerbi dashboards and thought this might be a quick and dirty way of getting a file with all of the data that I could consume in PBI!

**Comment by tobyweston** [comment]
I've been looking at a new menu widget and the ability to export from there? What do you think @singh763173 ?

![screenflow](https://user-images.githubusercontent.com/49573/34463256-4d3f41d0-ee4d-11e7-8157-02fc8ce1dd7f.gif)

**Comment by singh763173** [comment]
blimey - that's really impressive! is this in the latest release?

which graph does the export to csv feature provide?
