### ISSUE TITLE
PCB

### ISSUE THREAD

**Issue by Totoleheros** [tobyweston/temperature-machine#35]
On the http://temperature-machine.com web site, you mention the PBC that you have designed. It is pretty neat. I have found that it could be easy and cheap to order it from the JLCPCB website. Would it be possible to share the gerber file of your PCB?

**Comment by tobyweston** [comment]
Defo! 

I was actually planning to do a "manufacturing run" as I've had some interest. Have you had boards from JLC before? I used Seed before and thought they were good.

I'd actually like to revise the board design and maybe incorporate a breakout or additional sensors. Any ideas?

**Comment by Totoleheros** [comment]
No, just read good reviews on the web concerning this PCB maker. The board as it is right now sounds good enough for me and my needs, no further ideas to improve it.
Regards

**Comment by Totoleheros** [comment]
Any chance that you will share the gerber file of your current PCB?

**Comment by tobyweston** [comment]
The fritzing file is in with the source, you can generate the gerber files with fritzing...

Give me a shout if you have trouble.

**Comment by user7743** [comment]
I would be very interested if you did a run of the PCB's. They look very need and useful for this kind of project.

**Comment by tobyweston** [comment]
I've placed a little order, not sure when they'll come or the quality but happy to send a few out if you drop me a line.

**Comment by user7743** [comment]
Not sure how best to contact you Toby but you can mail me at [redacted] if you wish. Id be happy to pay for the PCB ;-)

**Comment by Totoleheros** [comment]
I have found the fritzing file in the source. Thank you so much!

**Comment by tobyweston** [comment]
I’ve done a small “manufacturing run” (grand title). Get it touch if you’d like one (DM on Twitter? @jamanifin)

**Comment by Totoleheros** [comment]
I got mine (n=10) from JLC 2 days ago. Very quick service, perfect packaging, perfect finish. And the best: for only 2€, all included (shipment too!)? I really do not know how they make money out of this business, something sounds wrong...At any rate, I'm very very happy with what I've got from them.

**Comment by tobyweston** [comment]
I know! I did the same. Not sure if this is prototype only as the price goes up for more. Still, very good value, I'm going to do a revision and get another lot done. Good tip, thanks! :+1:
