### ISSUE TITLE
Long term graphs title

### ISSUE THREAD

**Issue by Quaxo76** [tobyweston/temperature-machine#40]
I just updated to the latest available version. I noticed that when I click on one of the long range graphs, and it enlarges, at the top left of the screen I get the "title" of that graph (i.e. 24-hour or 1 week). If then I change to another graph using the left/right arrows on screen, the graph does change, but the title does not. It should change to constantly reflect what graph is being shown...

Cristian

**Comment by tobyweston** [comment]
Good spot. Will investigate

**Comment by tobyweston** [comment]
Fixed by https://github.com/tobyweston/temperature-machine-ui/commit/7ea30cfc4bf1db2ed18edd616b87d3b58b6a19e2

**Comment by Quaxo76** [comment]
Thank you, it works now. Could I also suggest to also add the descriptor to the actual graph? Where it says "temperature" on the top center of the graph, it could say "temperature 24 hours", "temperature 7 days" etc. This would be good especially since I'm storing the past graphs on the sd...

**Comment by tobyweston** [comment]
Fixed the second part and labeled the charts better.
