### ISSUE TITLE
Unwanted spurious spikes

### ISSUE THREAD

**Issue by Quaxo76** [tobyweston/temperature-machine#41]
My server has been behaving well, with no drops and no spikes. But the client, which has two sensors attached, sometimes shows large spikes, which are annoying especially because they mess up the autoscale of the y axis, and so I loose detail.
What is weird is that both sensors show the same spike, and it appears to be on only one frame. Could this be a communication error? It's hard to believe that both sensors always show the same spike at exactly the same moment...
![temperature](https://user-images.githubusercontent.com/35546248/35072368-908fe7f6-fbe4-11e7-82a0-39b4791f70c4.png)

![temperature2](https://user-images.githubusercontent.com/35546248/35072466-0057720c-fbe5-11e7-92c4-099519979e53.png)

**Comment by Quaxo76** [comment]
Just realized this is a duplicate of #9 . I tried to apply the proposed solution by modifying my startup command to
`su pi -c 'cd /home/pi/code/temperature-machine && ./start-client.sh -Davoid.spikes=30 &'`
and rebooted. I'll see if it helps...

Cristian

**Comment by tobyweston** [comment]
Great, make sure you get the latest version for that feature. When it's on, the log will show when it detected a spike and through the value away. Let me know if you see any.

This has been a huge pain for me as its hard to reproduce and I get it all the time across machines. I really have no idea at this point as the smoothing feature doesn't work for me (although its tested so works "in theory"). I've started to suspect electrical interference!

The new download CSV feature is partly there to help me figure out why the spikes aren't getting smoothed. Perhaps you could grab some images and CSV and attach to #9 and we'll see if it helps diagnose?

Closing this issue.
