### ISSUE TITLE
Data doesn't appear to be archiving

### ISSUE THREAD

**Issue by singh763173** [tobyweston/temperature-machine#51]
Previously had issues with the graphs but since pulling the latest commits the issue has since changed. 

The graph now does not update in any way shape or form and shows stale data which doesn't exist (i know it doesn't exist because i deleted the rrd file to see if that kicks it back into shape!)

also - not sure where the sensor name "bedroom1-sensor1" has come from!

<img width="1031" alt="screen shot 2018-01-20 at 19 07 55" src="https://user-images.githubusercontent.com/6620322/35187040-a14c07e0-fe15-11e7-8de9-772f7101820f.png">

**Comment by tobyweston** [comment]
I suspect running the tests dumped some test data (overriding your rrd file with 'bedroom-1'. Sorry about that. Try deleting your rrd and restarting. You can skip running tests next time (see http://temperature-machine.com/docs/getting_started/build_from_source.html#skipping-tests)

I'll leave this ticket open to try and figure out how to not interfere with production data from the tests.

**Comment by singh763173** [comment]
Bingo! Looks like it's back in action - cheers mate!
