### ISSUE TITLE
Make config for 'All/Averaged Sensors' sticky

### ISSUE THREAD

**Issue by Quaxo76** [tobyweston/temperature-machine#53]
One of my machines has two sensors, one of which is indoors and the other outdoors. Because of this, the average value between the two is rather meaningless to me, so I always check the "show all sensors" setting. But at every refresh, it reverts to the default behavior of averaging. Would it be possible to make it remember the last setting, or at least, set the default via config file?

**Comment by tobyweston** [comment]
Yep, on it. There's some sort of glitch I need to fix to make it 'sticky'. The site is built using React and I'm probably missing something.

Being React, I'm going for Single Page App (SPA) style where you shouldn't need to hit refresh, just navigate. There's a few things to do to get that working fully though. It's on my radar.
