### ISSUE TITLE
Create a Debian package for distribution

### ISSUE THREAD

**Issue by tobyweston** [tobyweston/temperature-machine#57]
Share the software via a Debian package available with `apt-get install temperature-machine` and `apt-get update temperature-machine`.

## Create the Package

* http://www.king-foo.com/2011/11/creating-debianubuntu-deb-packages/

## Making it Public

Looks like you have to serve a generate `Package` available on the internet, then get user's to add it to their `/etc/apt/sources.list`.

* https://linuxconfig.org/easy-way-to-create-a-debian-package-and-local-package-repository

**Comment by Quaxo76** [comment]
Toby, this would update the binaries and not the sources, right? It would be very welcome, since compiling at every new version takes about 30 minutes on each of my Zeros - and I have 4 of them to update...

**Comment by tobyweston** [comment]
## Things to do

- [x] Package binaries
- [x] Man pages
- [x] Config
- [ ] `systemd` setup
- [x] Startup scripts / migrate VM settings, JMX etc
- [ ] Logs (location etc)
- [x] ProGuard to reduce binary download size

**Comment by tobyweston** [comment]
Closed, 2.1 will be the first official release via apt-get
