### ISSUE TITLE
Use GZip compression

### ISSUE THREAD

**Issue by tobyweston** [tobyweston/temperature-machine#71]
Not sure why this wasn't done already...

https://http4s.org/v0.18/gzip/

**Comment by tobyweston** [comment]
I dunno, this kinda looks slower... before and after:

<img width="1040" alt="screen shot 2018-05-14 at 18 26 20" src="https://user-images.githubusercontent.com/49573/40013958-03612dd0-57a7-11e8-9ff3-4b0a2e01c80a.png">
<img width="1040" alt="screen shot 2018-05-14 at 18 43 52" src="https://user-images.githubusercontent.com/49573/40013960-037bd856-57a7-11e8-8829-a88532d33235.png">

**Comment by matty256** [comment]
Woohoo! Awesome reduction Toby!

-- Matt
