### ISSUE TITLE
Web interface does not remember preferences

### ISSUE THREAD

**Issue by awaspaas** [tobyweston/temperature-machine#75]
When I set the web interface to show all sensors instead of averaged, and when I set the timezone, these preferences are reset back to defaults the next time I visit the page.

**Comment by tobyweston** [comment]
Are you refreshing? It’s a single page app so don’t hit “refresh” or back, instead navigate via the menu

**Comment by awaspaas** [comment]
I apologize if I was unclear. No, I am not refreshing. Yes, changes are reflected immediately after I select a time zone or the individual sensors. Presently though, the time zone prefeference or the preference to see individual sensors are forgotten if I visit the page later. I would like those settings to persist so they remain the way they were set on subsequent visits to the webpage until they are changed again by the user.
