### ISSUE TITLE
2 servers on one network

### ISSUE THREAD

**Issue by AlistairFielden** [tobyweston/temperature-machine#97]
If two machines are set as server then clients will find one and then send data to that server. Would be useful in the config to define a specific IP /name that the client should attach to.

**Comment by tobyweston** [comment]
Not sure why you’d want to run two servers.

It’s designed to be run with one server and multiple clients. That’s configured the first time you run it and stored in a config file.

Can you elaborate why you’d want two servers. Thinking I’ll close the issue otherwise.

**Comment by AlistairFielden** [comment]
Currently I’ve run 2 so I can see in more detail one of the trends. On the main system I have internal and external trends and when the external temperature gets low then the resolution of the internal temperatures is not great. If you could turn pens on and off as per my other request then this requirement would disappear.
 
-- 
Regards,
Alistair Fielden

**Comment by tobyweston** [comment]
Sorry I’m still not clear. You have server 1 with 2 probs (outside and inside) and server 2 with its own outside prob? Because the chart lines will compete and skew the scale?
