### ISSUE TITLE
Turn pens on/off

### ISSUE THREAD

**Issue by AlistairFielden** [tobyweston/temperature-machine#98]
It would be nice to be able to turn on and off pens on the chart (and rescale the y-axis appropriately) from within the browser.

**Comment by tobyweston** [comment]
Not sure what you mean by pen. But you can remove a probs chart by clicking on the name in the chart. So if you’re tracking two lines, you can display 1 or both.

**Comment by AlistairFielden** [comment]
Forget it….. I’d not realised that you could click on the legend to toggle pens on and off. Perhaps this needs mentioning somewhere (unless I’ve missed it).
Keep up the good work.
